version: '3'

services:
  php-fpm:
    build:
      context: ./.docker/fpm
    depends_on:
      - db
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-app}_fpm
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-e5f54688edefaeb69243e047b2a76955}
      DATABASE_URL: ${DATABASE_DSN:-postgres://postgres:password@db:5432/postgres}
      APP_TIMEZONE: ${APP_TIMEZONE:-America/Montevideo}
      APP_SERVER_NAME: ${APP_SERVER_NAME:-localhost.docker}
    volumes:
      - ./api:/var/www
  nginx:
    build:
      context: ./.docker/nginx
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-e5f54688edefaeb69243e047b2a76955}
      DATABASE_URL: ${DATABASE_DSN:-postgres://postgres:password@db:5432/postgres}
      APP_TIMEZONE: ${APP_TIMEZONE:-America/Montevideo}
      APP_SERVER_NAME: ${APP_SERVER_NAME:-localhost.docker}
    volumes:
      - ./var/logs/nginx:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - ${HOST_HTTP_PORT:-80}:80
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-app}_nginx
  db:
    image: postgres:15.1
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-app}_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${HOST_DB_PORT:-5432}:5432
    volumes:
       - ./var/postgres:/var/lib/postgresql/data:rw