version: '3'

services:
  php-fpm:
    build:
      context: ./.docker/fpm
    depends_on:
      - db
    env_file: ./.docker/env.yml
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-app}_fpm
    volumes:
      - ./api:/var/www
    networks:
      - internal
  nginx:
    build:
      context: ./.docker/nginx
    env_file: ./.docker/env.yml
    volumes:
      - ./var/logs/nginx:/var/log/nginx
    depends_on:
      - php-fpm
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-app}_nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME:-app}.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME:-app}.rule=Host(`${APP_SERVER_NAME:-app.localhost}`)"
    networks:
      - internal
      - proxy
  db:
    image: postgres:15.1
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-app}_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
       - ./var/postgres:/var/lib/postgresql/data:rw
    networks:
      - internal

networks:
  proxy:
    name: traefik-proxy
    external: true
  internal:
    name: internal