version: '3'

services:
  php-fpm:
    build:
      context: ./.docker/fpm
    depends_on:
      - db
    env_file: ./.docker/env.yml
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-app}_fpm
    volumes:
      - ./api:/var/www
  nginx:
    build:
      context: ./.docker/nginx
    env_file: ./.docker/env.yml
    volumes:
      - ./var/logs/nginx:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - ${HOST_HTTP_PORT:-80}:80
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-app}_nginx
  db:
    image: postgres:15.1
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-app}_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${HOST_DB_PORT:-5432}:5432
    volumes:
       - ./var/postgres:/var/lib/postgresql/data:rw